lib/events.js
lib/leader.js

create events
implement ability to skip data persistence by specifying query string parameter

create events stream. ability to skip persistence

---

application.js
lib/cli.js
lib/providers/vagrant.js
npm-shrinkwrap.json
package.json

begins implementing cloud subcommands such as login, logout, list-clusters, create-cluster, destroy-cluster, etc

supports nomnom subcommands

---

lib/cli.js
lib/follower.js
npm-shrinkwrap.json
package.json

* implements builds cli subcommand
* add follower registry auth configuration

adds integration with ContainerShip Cloud build service

---

lib/leader.js

@nicktate pending containership/containership.cloud.loadbalancer#3

syncs cloud loadbalancers to myriad-kv

---

cluster_discovery.js

moves cluster_id file under /opt/containership

---

lib/cli.js

needs: https://github.com/containership/containership.cloud.auth/pull/17
@normanjoyner @nicktate

add support for bitbucket login

---

cluster_discovery.js

adds gce ip parsing

---

cluster_discovery.js

fix azure conditional

---

application.js
cluster_discovery.js
lib/cli.js
lib/constants.js
lib/follower.js
lib/integrations/github.js
lib/leader.js

@normanjoyner 
Take a look at this one pretty good, I didn't test this yet but it should just be straight forward replaces as long as I didn't add in any typos.

dynamically choose base urls for auth, build, and cloud apis

---

lib/follower.js

Volume id bug

---

application.js
cluster_discovery.js
lib/cli.js
lib/constants.js
lib/follower.js
lib/integrations/github.js
lib/leader.js
npm-shrinkwrap.json
package.json

Integrate containership.cloud.constants

---

cluster_discovery.js
lib/firewall.js
lib/leader.js
lib/myriad.js
npm-shrinkwrap.json
package.json

implements base firewall configuration on leader nodes

Adds initial firewall implementation

---

npm-shrinkwrap.json
package.json

bump constants version to 1.1.7

---

lib/firewall.js
lib/follower.js
lib/leader.js
lib/ssh_keys.js

sync and write containership ssh keys

---

lib/leader.js

add apps and hosts to register call body

---

lib/follower.js

Update registry checks for image auth

---

lib/cli-v2.js
package.json
yarn.lock

Depends on https://github.com/containership/containership.cloud.postgres/pull/6
@normanjoyner @mikestoltz

Added support for account metadata updating

---

index.js
lib/cloud-plugin.js
lib/ssh_keys.js

* syncs firewalls to distributed state store
* syncs ssh keys to distributed state store
* fixes registry url path
* cleans up styling
* implement Containership firewalls
* implement Containership SSH key management

sync firewalls, registries and ssh keys to distributed state store

---

lib/cloud-plugin.js

Formatting overhaul

---

lib/cloud-plugin.js
lib/utils.js

depends on containership/containership.k8s.api-bridge#29

set containership cloud specific environments in pre-deploy middleware

---

lib/cloud-plugin.js

Update registerCluster to fetch the public_ip from the leader

---

lib/cloud-plugin.js
lib/firewall.js

@normanjoyner @jeremykross @ashleyschuett 
Depends on https://github.com/containership/containership.k8s.api-bridge/pull/41
Still running into some issues where it is not getting updated on the forward chain sporadically for some reason. Need to dig into this a little more.

added forward chain logic for kubernetes

---

lib/firewall.js

support services running in host mode

---

lib/firewall.js

use configured flannel info

---

lib/firewall.js

- added logging error so we can see any errors when flushing, creating, and adding chains for input and forward
- added retry logic so if chain is not added it will try again every 30 seconds for 5 minutes

update chain rules to retry on error

---

lib/cli-v2.js

Removes third-party authentication in favor of newer Containership Cloud personal access tokens.
Fixes #141

Change account login command to accept Containership Cloud personal access token

---

lib/follower.js

fix registries default to be array
